--!strict

local CarryConfig = {
	PickupDistance = 8,
	PlacementDistance = 12,
	ServerDistanceTolerance = 1,
	CarryDistance = 3.5,
	RequestCooldown = 0.15,
	PlacementRayDistance = 30,
	PlacementSurfaceNormalMinY = 0.7,
	PlacementOverlapShrink = 0.1,
	PlacementSurfaceProbeAbove = 0.5,
	PlacementSurfaceProbeBelow = 0.75,
	PlacementSurfaceHeightTolerance = 0.2,
	PlacementOrientationDotTolerance = 0.9999,
	RotationStepDegrees = 90,
	RotationStepCount = 4,
	DefaultFreeStackMaxHeight = 8,
	StackCenterTolerance = 0.15,
	StackContactTolerance = 0.15,
	StackHeightTolerance = 0.05,
	SlotContainmentTolerance = 0.05,
	SlotProbeInset = 0.05,
	PalletFootprintTolerance = 0.05,
	PalletPackingGap = 0.05,
	PalletCandidateCoordinateEpsilon = 0.001,
	PalletCargoProbeDistance = 10,
	PackedPalletObjectName = "PackedPallet",
	PlacementPositionTolerance = 0.2,
	GhostTransparency = 0.65,
	RemotesFolderName = "Remotes",
	RemoteEventName = "CarryRequest",
	CarryingAttributeName = "IsCarryingItem",
}

return table.freeze(CarryConfig)
